# Generated by Django 3.0.7 on 2020-06-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='description',
            field=models.CharField(blank=True, max_length=100, verbose_name='설명이다~~~'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='hi',
            field=models.CharField(blank=True, max_length=100, verbose_name='실험'),
        ),
    ]
